import styles from "./sidebar.module.scss";
import { useAppDispatch, useAppSelector } from "@app/store/hooks";
import { setCollapsed } from "@app/store/collepsedSlice/collepsedSlice";
import { classNames } from "@shared/lib";

export function Sidebar() {
  const { collapsed } = useAppSelector((state) => state.collepsedSlice);
  const dispatch = useAppDispatch();

  return (
    <div
      className={classNames(styles.sidebar, {
        [styles.sidebarCollapsed]: collapsed,
      })}
    >
      <div>
        <button onClick={() => dispatch(setCollapsed())}>
          toggle siderbar
        </button>
        <p>sidebar one</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar</p>
        <p>sidebar end</p>
      </div>
    </div>
  );
}
